services:
  app:
    build: .
    container_name: viewers_leaderboard_frontend
    ports:
      - "3000:80"
    environment:
      VITE_API_BASE_URL: http://localhost:8000
      VITE_FORCE_CHANNEL_ID: 1230
    env_file:
      - .env